### ISSUE TITLE
CSS - too many messages creates bug

### ISSUE THREAD

**Issue by Slluxx** [demian85/electron-chat-app-demo#1]
If you write a few messages till it reaches the input bar and you type a few more, you will see that the `<p>` tags are going "under" the input bar. Also the input bar gets weirdly distorted.

![ss 2017-10-03 at 02 16 21](https://user-images.githubusercontent.com/15162905/31124691-d7db14e8-a845-11e7-9f50-33153b6034a6.png)

In gerneral this construct seems very unclear to me. Why not just prebuild the HTML and then get those element and fill? I hope after all this time you might fix this. This is the only working demo out there and id like to use it for a private project.

Best regards,
Slluxx

**Comment by demian85** [comment]
This project is for demonstration purposes only, and it was made almost a year ago. You are welcome to submit a PR with the fix.
Also, looks like `overflow: auto` is missing somewhere. That should be an easy fix.

**Comment by Slluxx** [comment]
yeah i already fixed that one. 

but could you explain why its easier to create the elements in code instead of getting the id of a prebuild html?

**Comment by demian85** [comment]
Well, you would need to read about React and component oriented frameworks
