### ISSUE TITLE
Can't edit server endpoint

### ISSUE THREAD

**Issue by RafagaQueiroz** [demian85/electron-chat-app-demo#4]
How do I edit the server endpoint?

**Comment by ameya98** [comment]
Probably too late, but if anyone is interested, I made a fork which allows the server to be hosted on Heroku (and also has better styling) at https://github.com/ameya98/electron-chat-app-demo

**Comment by demian85** [comment]
Good for you. Is this an issue?
I don't support this app anymore since it is clearly a demo app for an interview. It's almost 4 years old.

**Comment by ameya98** [comment]
Thanks for the project!
